SELECT DISTINCT NAME, POSITION
FROM EMPLOEE
WHERE DEPARTMENT_ID = 1;

----------------------------------------------

SELECT NAME
FROM EMPLOYEE EMP1 
WHERE EMP1.SALARY >= 2 * (SELECT AVG(SALARY) FROM EMPLOYEE EMP2 WHERE EMP2.CHIEF_ID = EMP1.ID);
